runtime: nodejs18

env_variables:
  # EMAIL_SERVICE: gmail
  # EMAIL_USER: dharunsivakumar002@gmail.com
  # EMAIL_PASS: qgfibvaxitsnuruu

  EMAIL_SERVICE: gmail
  EMAIL_USER: kcgethereal@gmail.com
  EMAIL_PASS: bwcjwrwlzieheycd

  STRIPE_PUBLIC_KEY: pk_live_51J30NfSFg7MvYkkayugYw3ZEluSHO322PRW98ZcmbHq4H3TWNicKnUmBw5mni6TR9ltnRIy8BCqLLJsZ7rbHYDpw00V0pqkNOO
  STRIPE_SECRET_KEY: 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
  STRIPE_TEST_PUBLIC_KEY: pk_test_51J30NfSFg7MvYkkapYPrerJ06A8ebX7nj2EOwoe69B0GIhUhxFdegNFjaxMgXSjcDmnnhcnNnWhhGb1sVG4LNJhl00VMnW4MST
  STRIPE_TEST_SECRET_KEY: sk_test_51J30NfSFg7MvYkkaxnhEKd62WA4ACbJDxaQGZuYzcFtFObzrLe5B2Rwqr7igavbuZ9AJXN0PkcOLi1rkgqT2ZjtU00EagS6IKX

  PG_HOSTNAME: "dpg-ck18e5mru70s73bke290-a"
  PG_PORT: 5432
  PG_DATABASE: "ethereal"
  PG_USERNAME: "ethereal_user"
  PG_PASSWORD: "NClADc5N3zdbShrczXfCmDcuu7tFFSfG"
  PG_INTERNAL_DATABASE_URL: "postgres://ethereal_user:NClADc5N3zdbShrczXfCmDcuu7tFFSfG@dpg-ck18e5mru70s73bke290-a/ethereal"
  PG_EXTERNAL_DATABASE_URL: "postgres://ethereal_user:NClADc5N3zdbShrczXfCmDcuu7tFFSfG@dpg-ck18e5mru70s73bke290-a.singapore-postgres.render.com/ethereal"

  PRICE_ETHEREAL: "price_1NpdLvSFg7MvYkkaUKiB4afQ"
  PRICE_IC_CONCERT: "price_1NpdLfSFg7MvYkkaEOPyaTz0"
  PRICE_OC_CONCERT: "price_1NpdLXSFg7MvYkkadCdSWuAt"
  PRICE_IC_COMBO_CONCERT: "price_1NpdLoSFg7MvYkka956kXlLA"
  PRICE_OC_COMBO_CONCERT: "price_1NpdLlSFg7MvYkkaG685HCnN"
