export const pages = [
  {
    name: "Home",
    path: "/",
    show: true,
  },
  {
    name: "Events",
    path: "/events",
    show: true,
  },
  {
    name: "Schedule",
    path: "/schedule",
    show: true,
  },
  {
    name: "Team",
    path: "/team",
    show: true,
  },
  {
    name: "Contact",
    path: "/contact",
    show: true,
  },
  {
    name: "Profile",
    path: "/profile",
    show: true,
  },
];

const depts = {
  it: "Information Technology",
  ad: "Artificial Intelligence ",
  cs: "Computer Science ",
  ft: "Fashion Technology",
  ae: "Aeronautical",
  at: "Automobile",
  ce: "Civil",
  ec: "Electronics & Comm ",
  ee: "Electrical & Electronic ",
  ei: "Electronics & Instruments ",
  mc: "Mechatronics",
  ao: "Aerospace",
  me: "Mechanical",
  sh: "Science & Humanities",
};

export const colleges = [
  "Aalim Muhammed Salegh College of Engineering, Chennai",
  "Aarupadai Veedu Institute of Technology, Kanchipuram",
  "Agni College of Technology, Chennai",
  "B.S. Abdur Rahman University (B.S. Abdur Rahman Crescent Engineering College), Chennai",
  "Bharath University (Bharath Institute of Higher Education and Research), Chennai",
  "Chennai Institute of Technology, Chennai",
  "Dhanalakshmi College of Engineering, Chennai",
  "Dr. MGR University (Dr. M.G.R. Educational and Research Insitute), Chennai",
  "Easwari Engineering College, Chennai",
  "G.K.M. College of Engineering and Technology, Chennai",
  "Hindustan University (Hindustan College of Engineering), Chennai",
  "Jerusalem College of Engineering, Chennai",
  "K.C.G. College of Technology, Chennai",
  "Meenakshi Sundararajan Engineering College, Chennai",
  "PERI Institute of Technology, Chennai",
  "Raja Rajeswari Engineering College, Chennai",
  "S.A. Engineering College, Thiruverkadu",
  "S.K.R. Engineering College, Thiruvallur",
  "Sree Sastha Institute of Engineering and Technology, Chennai",
  "Sri Lakshmi Ammal Engineering College, Chennai",
  "Sri Sai Ram Institute of Technology, Chennai",
  "Sri Sairam Engineering College, Chennai",
  "St. Peter's University (St. Peters Engineering College), Chennai",
  "T.J. Institute of Technology, Chennai",
  "Tagore Engineering College, Chennai",
  "Thangavelu Engineering College, Chennai",
  "Central Institute of Plastic Engineering and Technology (CIPET), Chennai",
  "University Departments of Anna University Chennai, ACT Campus, Chennai",
  "University Departments of Anna University Chennai, CEG Campus, Chennai",
  "University Departments of Anna University Chennai, MIT Campus, Chennai",
  "Alpha College of Engineering, Chennai",
  "Anand Institute of Higher Technology, Chengalpattu Taluk",
  "Annai Veilankanni's College of Engineering, Chennai",
  "Central Institute of Plastics Engineering and Technology, Chennai",
  "Davinci School of Design and Architecture, Chennai",
  "Dhaanish Ahmed College of Engineering, Chennai",
  "Gojan School of Business and Technology, Chennai",
  "Gopal Ramalingam Memorial Engineering College, Chennai",
  "Jawahar Engineering College, Chennai",
  "Jeppiaar Engineering College, Chennai",
  "Loyola-ICAM College of Engineering and Technology, Chennai",
  "Madha Engineering College, Chennai",
  "Madha Institute of Engineering and Technology, Chennai",
  "Magna College of Engineering, Tiruvallur",
  "Measi Academy of Architecture, Chennai",
  "Meenakshi College of Engineering, Chennai",
  "Misrimal Navajee Munoth Jain Engineering College, Chennai",
  "Mohamed Sathak A.J. College of Engineering, Chengelpet Taluk",
  "Mohammed Sathak A J Academy of Architecture, Chennai",
  "New Prince Shri Bhavani College of Engineering and Technology, Chennai",
  "P.M.R. Engineering College, Chennai",
  "Panimalar Engineering College, Chennai",
  "Panimalar Institute of Technology, Chennai",
  "Prince Dr. K. Vasudevan College of Engineering and Technology, Chennai",
  "Prince Shri Venkateshwara Padmavathy Engineering College, Chengalpet",
  "S.R.R. Engineering College, Chengalpattu",
  "Sathyabama University (Sathyabama Engineering College), Chennai",
  "School of Architecture St.Peter's College of Engineering & Technology, Chennai",
  "Sree Sastha College of Engineering, Chennai",
  "Sri Krishna Engineering College, Sriperumpudur",
  "Sri Krishna Institute of Technology, Chennai",
  "Sri Muthukumaran Institute of Technology, Chennai",
  "Sri Ramanujar Engineering College, Chennai",
  "Sri Sivasubramaniya Nadar College of Engineering, Chennai",
  "Srinivasa Institute of Engineering and Technology, Chennai",
  "St. Joseph's College of Engineering, Kanchipuram",
  "St. Peter's College of Engineering and Technology, Chennai",
  "University Departments of Anna University Chennai, SAP Campus, Chennai",
  "Vel Tech, Chennai",
  "Vel Tech Dr.RR and Dr.SR Technical University (Vel Tech Engineering College), Chennai",
  "Vel Tech High Tech Dr.Rangarajan Dr.Sakunthala Engineering College, Chennai",
  "Vel Tech Multi Tech Dr.Rangarajan Dr.Sakunthala Engineering College, Chennai",
  "Velammal Engineering College, Chennai",
  "Asan Memorial College of Arts and Science, Chennai",
  "Bhaktavatsalam Memorial College for Women, Chennai",
  "Meenakshi College for Women, Chennai",
  "Sriram College of Arts and Science, Chennai",
  "Tagore College of Arts and Science, Chennai",
  "Vels University (Vel's College of Science), Chennai",
  "A.M. Jain College (Men), Chennai",
  "Bharathi's Women's College (Autonomous), Chennai",
  "C. Kandasami Naidu College for Men, Chennai",
  "Chellammal Women's College of the Pachaiyappa's Trust, Chennai",
  "Dhanraj Baid Jain College (Autonomous), Chennai",
  "Dharmamurthi Rao Bahadur Calavala Cunnan Chetty's Hindu (D.R.B.C.C.C.H.) College, Chennai",
  "Dr. Ambedkar Government Arts College, Chennai",
  "Dwaraka Doss Goverdhan Doss Vaishnav College, Chennai",
  "Ethiraj College for Women (Autonomous), Chennai",
  "Govt. Arts College for Men (Autonomous), Chennai",
  "Guru Nanak College, Chennai",
  "Justice Basheer Ahmed Syed College for Women, Chennai",
  "Loyola College (Autonomous), Chennai",
  "Madras Christian College (Autonomous), Chennai",
  "New College (Autonomous), Chennai",
  "Pachaiyappa's College, Chennai",
  "Presidency College (Autonomous), Chennai",
  "Quaid-e-Millet College, Chennai",
  "Quaid-e-Millet Government Arts College for Women (Autonomous), Chennai",
  "Queen Mary's College (Autonomous), Chennai",
  "Ramakrishna Mission Vivekananda College (Men), Chennai",
  "S.D.N. Bhatt Vaishnav College for Women, Chennai",
  "S.I.V.E.T. College, Chennai",
  "St. Louis College for the Deaf, Chennai",
  "Stella Maris College for Women (Autonomous), Chennai",
  "Women's Christian College (Autonomous), Chennai",
  "A.A. Arts and Science College (Women), Chennai, Chennai",
  "Alpha Arts and Science College, Chennai",
  "Anna Adarsh College for Women, Chennai",
  "Annai Veilankanni's College of Arts and Science, Chennai",
  "Annai Violet Arts and Science College, Chennai",
  "C.T.M. College of Arts and Science, Chennai",
  "Chennai National College (Arts and Science), Chennai",
  "Chevaliar T. Thomas Elizabeth College for Women, Chennai",
  "Dr. M.G.R. Janaki College of Arts and Science for Women, Chennai",
  "Guru Shree Shanti Vijai Jain College for Women, Chennai",
  "Hindustan College of Arts and Science, Kelambakkam",
  "Indian Harvard Arts and Science College, Chennai",
  "J.A. Arts and Science College, Chennai",
  "Jayagovind Harigopal Agarwal Agarsen College, Chennai",
  "K.C.S. Kasi Nadar College of Arts and Science, Chennai",
  "Kumara Rani Meena Muthiah College of Arts and Science for Women, Chennai",
  "M.O.P. Vaishnav College for Women (Autonomous), Chennai",
  "Madha Arts and Science College, Chennai",
  "Mahalakshmi College of Arts and Science, Chennai",
  "Mar Gregorios Arts and Science College, Chennai",
  "Mohamed Sathak College of Arts and Science, Chennai",
  "Nazareth College of Arts and Science, Chennai",
  "New Prince Shri Bhavani Arts and Science College, Chennai",
  "Patrician College of Arts and Science, Chennai",
  "Poonga College of Arts and Science, Chennai",
  "Prince Shri Venkateshwara Arts and Science College, Chennai",
  "Prof. Dhanapalan College for Women, Chennai",
  "R.B. Gothi Jain College for Women, Chennai",
  "S.R.M. Arts and Science College, Chengalpattu Taluk",
  "Shri Shankarlal Sundarbai Shasun Jain College for Women, Chennai",
  "Sindhi College of Arts and Science, Chennai",
  "Sir Theagaraya College, Chennai",
  "Soka Ikeda Arts and Science College for Women, Chennai",
  "Sri Kanniga Parameswari Arts and Science College for Women, Chennai",
  "Sri Muthukumarasamy College, Chennai",
  "St. Joseph's College (Arts and Science), Chennai",
  "St. Thomas College of Arts and Science, Chennai",
  "T.M.G. College of Arts and Science, Chennai",
  "T.S. Narayanasamy College of Arts and Science, Chennai",
  "Tamilnadu Arts and Science College, Chennai",
  "Thirumurugan College of Arts and Science, Thiruvallur",
  "Thiruthangal Nadar College, Chennai",
  "Vailakanni Malathy Pannicker College of Arts and Science, Chennai",
  "Valliammal College for Women, Chennai",
  "Vel Sri Ranga Sanku College, Chennai",
  "Women's Christian College (Autonomous), Chennai",
  "Dr. MGR University (Thai Moogambigai Dental College and Hospital), Chennai",
  "S.R.M. Dental College and Hospital, Chennai",
  "Saveetha University (Saveetha Dental College and Hospital), Chennai",
  "Sree Balaji Dental College and Hospital, Chennai",
  "Tamilnadu Govt. Dental College, Chennai",
  "Madha Dental College and Hospital, Chennai",
  "Meenakshi University (Meenakshi Ammal Dental College and Hospital), Chennai",
  "Ragas Dental College and Hospital, Chennai",
  "Sri Ramachandra University (Sri Ramachandra Dental College), Chennai",
  "Tagore Dental College and Hospital, Chennai",
  "A.C.S. Medical College and Hospital, Chennai",
  "Sree Balaji Medical College and Hospital, Chennai",
  "SRM Medical College Hospital and Research Centre, Chennai",
  "Cancer Institute, College of Oncological Sciences, Chennai",
  "Dr. A.L.M. PG Institute of Basic Medical Sciences, Chennai",
  "Kilpauk Medical College, Chennai",
  "Madras Medical College and Research Institute, Chennai",
  "Stanley Medical College, Chennai",
  "Sankara Nethralaya Medical Research Foundation, Chennai",
  "Sri Ramachandra University (Sri Ramachandra Medical College and Research Institute), Chennai",
  "Aalim Muhammed Salegh Polytechnic College, Chennai",
  "Sri Sairam Polytechnic College, Chennai",
  "A.M.K Technology Polytechnic College, Chennai",
  "Central Polytechnic College, Chennai",
  "Dr. Dharmambal Government Polytechnic College for Women, Chennai",
  "Government Polytechnic College, Chennai",
  "Government Technical Training Centre, Chennai",
  "Institute of Chemical Technology, Chennai",
  "Institute of Leather Technology, Chennai",
  "Institute of Printing Technology, Chennai",
  "Institute of Textile Technology, Chennai",
  "M.G.R Government Film and T.V. Institute of Tamilnadu, Chennai",
  "P.T. Lee Chengalvaraya Naicker Polytechnic College, Chennai",
  "Ramakrishna Mission Technical Institute, Chennai",
  "Regional Labour Institute, Taramani",
  "State Institute of Commerce Education, Chennai",
  "Hindustan Institute of Engineering Technology, Chennai",
  "Institute of Road Transport Polytechnic College, Chennai, Tambaram",
  "Meenakshi Krishnan Polytechnic College, Chennai",
  "Panimalar Polytechnic College, Chennai",
  "Siga Polytechnic College, Chennai",
  "Sri Balaji Polytechnic College, Chennai",
  "Sri Nallalaghu Polytechnic College, Chennai",
  "Thai Moogambigai Polytechnic College, Chennai",
  "Thiru Seven Hills Polytechnic College, Chennai",
  "V. Ramakrishna Polytechnic College, Chennai",
];

export const events = [
  {
    eventId: "event_1f98aad5-3685-4033-a9a6-566057302682",
    name: "BATTLE OF BANDS",
    mode: "offline",
    min: 4,
    max: 8,
    coordinators: [
      { name: "SRIDHARAN", phone: "8754461886" },
      { name: "KALOOSH", phone: "7338803892" },
    ],
    rules: 1,
  },
  {
    eventId: "event_28c1c57d-ff64-47e0-99a3-9b378578b695",
    name: "RAMP WALK",
    mode: "offline",
    min: 6,
    max: 8,
    coordinators: [
      { name: "BOOMIKA", phone: "6379054670" },
      { name: "MONICA", phone: "9384620296" },
    ],
    rules: 1,
  },
  {
    eventId: "event_d8a43e96-7dac-41a1-b448-54c2d8f34686",
    name: "ADZAP",
    mode: "offline",
    min: 4,
    max: 6,
    coordinators: [
      { name: "SURIYALAKSHMI", phone: "6369251768" },
      { name: "MADHUMITTHA", phone: "8940478857" },
    ],
    rules: 1,
  },
  {
    eventId: "event_99726930-71fb-4992-869d-698a2837bb6a",
    name: "LIGHTS, CAMERA, ACTION",
    mode: "offline",
    min: 6,
    max: 10,
    coordinators: [
      { name: "SURAJ", phone: "9150794919" },
      { name: "SUSHMITHA", phone: "8428843127" },
    ],
    rules: 2,
  },
  {
    eventId: "event_75aa601b-fc10-466c-9eef-db6c96529465",
    name: "VARIETY",
    mode: "offline",
    min: 4,
    max: 10,
    coordinators: [
      { name: "MADHUMITHA", phone: "8778478168" },
      { name: "RAMANAN", phone: "9445579086" },
    ],
    rules: 1,
  },
  {
    eventId: "event_c8348126-fc6e-46ae-a2d4-b5b51703ce46",
    name: "60 SECS TO FAME",
    mode: "offline",
    min: 1,
    max: 1,
    coordinators: [
      { name: "ALLEN", phone: "9150259188" },
      { name: "SARUP", phone: "9150270456" },
    ],
    rules: 2,
  },
  {
    eventId: "event_d7891e4c-cb20-4bc9-bdfd-973d6659eccd",
    name: "BLOCK & TACKLE",
    mode: "offline",
    min: 1,
    max: 1,
    coordinators: [
      { name: "ATHUL", phone: "9061228830" },
      { name: "GOKUL", phone: "8089407747" },
    ],
    rules: 1,
  },
  {
    eventId: "event_ea440cc0-796b-4262-80cb-40def6895937",
    name: "RAP BATTLE",
    mode: "offline",
    min: 1,
    max: 1,
    coordinators: [
      { name: "SHAANAL", phone: "9080552022" },
      { name: "DHANUSH", phone: "7358676220" },
    ],
    rules: 1,
  },
  {
    eventId: "event_bf6c046b-535c-459d-9017-1ad75fb5c53b",
    name: "SOLO SINGING",
    mode: "offline",
    min: 1,
    max: 1,
    coordinators: [
      { name: "VAIBHAV", phone: "7340955753" },
      { name: "SUSHMITHA", phone: "8056649106" },
    ],
    rules: 1,
  },
  {
    eventId: "event_9d88c35e-6e55-451f-abab-16f208894dcb",
    name: "SHORT FILM",
    mode: "online",
    min: 1,
    max: 4,
    coordinators: [
      { name: "FAZIL", phone: "8939421490" },
      { name: "SILAMBARASAN", phone: "9941041632" },
    ],
    rules: 2,
  },
  {
    eventId: "event_7b55020c-6719-433e-9d69-36e4a06d1c4e",
    name: "DEBATE",
    mode: "offline",
    min: 1,
    max: 2,
    coordinators: [
      { name: "PREM", phone: "8637687106" },
      { name: "SRIRAM", phone: "8778544662" },
    ],
    rules: 2,
  },
  {
    eventId: "event_b14fae3f-0eec-4881-9a37-1f12adc53748",
    name: "DUMB CHARADES",
    mode: "offline",
    min: 1,
    max: 4,
    coordinators: [
      { name: "SAMUEL", phone: "7397442337" },
      { name: "GIRIDHARAN", phone: "6380102078" },
    ],
    rules: 1,
  },
  {
    eventId: "event_9589001c-8d5d-491b-b23a-da331b8c28e6",
    name: "MEME CREATION",
    mode: "offline",
    min: 1,
    max: 1,
    coordinators: [
      { name: "ABI", phone: "8098839376" },
      { name: "SATHISH", phone: "8072369557" },
    ],
    rules: 1,
  },
  {
    eventId: "event_ca2bcb76-7e81-4bb7-83fd-2dcd13eb248a",
    name: "JAM",
    mode: "offline",
    min: 1,
    max: 1,
    coordinators: [
      { name: "SIVARAMAN", phone: "8754575236" },
      { name: "KARUPAIYAH", phone: "7708902768" },
    ],
    rules: 2,
  },
  {
    eventId: "event_ce82da20-5f5e-4198-add6-53bbea7789be",
    name: "BOX CRICKET",
    mode: "offline",
    min: 6,
    max: 8,
    coordinators: [
      { name: "SHAFUIR", phone: "8925310528" },
      { name: "RUDHRA", phone: "9551341891" },
    ],
    rules: 1,
  },
  {
    eventId: "event_eac94114-df6c-4efa-bdd5-a9ad8edcc981",
    name: "BGMI",
    mode: "Online",
    min: 4,
    max: 4,
    coordinators: [
      { name: "RAVINDRANATH", phone: "8754213503" },
      { name: "PRASANTH", phone: "9566228671" },
    ],
    rules: 1,
  },
  {
    eventId: "event_5037d596-b853-47fe-8fe1-c9c54cb1bb5d",
    name: "FREEFIRE",
    mode: "online",
    min: 4,
    max: 4,
    coordinators: [
      { name: "MASHA", phone: "979094967" },
      { name: "RAMANAN", phone: "6374379114" },
    ],
    rules: 2,
  },
  {
    eventId: "event_6853b2b1-bffd-4bb1-b066-96225fae6caf",
    name: "VALORANT",
    mode: "online",
    min: 4,
    max: 4,
    coordinators: [
      { name: "VANSHAJ", phone: "8738827279" },
      { name: "RANJITH", phone: "8939335386" },
    ],
    rules: 2,
  },
  {
    eventId: "event_c76726c4-fe91-4404-a611-d8c03a9d9def",
    name: "MR & MS ETHEREAL",
    mode: "offline",
    min: 1,
    max: 1,
    coordinators: [
      { name: "", phone: "" },
      { name: "", phone: "" },
    ],
    rules: 1,
  },
  {
    eventId: "event_ed638054-21d0-43e6-9c0b-9a28c50ce4bc",
    name: "GROUP DANCE",
    mode: "offline",
    min: 7,
    max: 12,
    coordinators: [
      { name: "", phone: "" },
      { name: "", phone: "" },
    ],
    rules: 1,
  },
  {
    eventId: "event_954ea9b5-f576-4809-9437-06ab03ec99d8",
    name: "CHANNEL SURFING",
    mode: "offline",
    min: 4,
    max: 6,
    coordinators: [
      { name: "", phone: "" },
      { name: "", phone: "" },
    ],
    rules: 1,
  },
  {
    eventId: "event_eb188b17-4899-4076-b1cf-4d7ea9c8d6a8",
    name: "MIME",
    mode: "offline",
    min: 4,
    max: 6,
    coordinators: [
      { name: "", phone: "" },
      { name: "", phone: "" },
    ],
    rules: 1,
  },
  {
    eventId: "event_f7223dbc-14b0-4ce1-82b7-17bc82c540dc",
    name: "MONO ACTING",
    mode: "offline",
    min: 1,
    max: 1,
    coordinators: [
      { name: "", phone: "" },
      { name: "", phone: "" },
    ],
    rules: 2,
  },
  {
    eventId: "event_d141c42f-6be0-4008-a678-5aeda4e15efb",
    name: "DANCE BATTLE",
    mode: "offline",
    min: 2,
    max: 2,
    coordinators: [
      { name: "", phone: "" },
      { name: "", phone: "" },
    ],
    rules: 1,
  },
  {
    eventId: "event_9230cd66-2703-42d2-a780-e8a4ff28d765",
    name: "SHIPWRECK",
    mode: "offline",
    min: 1,
    max: 1,
    coordinators: [
      { name: "", phone: "" },
      { name: "", phone: "" },
    ],
    rules: 1,
  },
  {
    eventId: "event_a82a4c5a-9844-4e45-8b2f-246cee79c61b",
    name: "GREEN SCREEN",
    mode: "offline",
    min: 1,
    max: 1,
    coordinators: [
      { name: "", phone: "" },
      { name: "", phone: "" },
    ],
    rules: 1,
  },
  {
    eventId: "event_79379dba-b15b-4d60-9107-7503940a3395",
    name: "IPL AUCTION",
    mode: "offline",
    min: 5,
    max: 5,
    coordinators: [
      { name: "", phone: "" },
      { name: "", phone: "" },
    ],
    rules: 1,
  },
  {
    eventId: "event_36aacf08-8f06-4a9d-a099-bf0ff449db0c",
    name: "QUIZ",
    mode: "offline",
    min: 4,
    max: 4,
    coordinators: [
      { name: "", phone: "" },
      { name: "", phone: "" },
    ],
    rules: 1,
  },
  {
    eventId: "event_d96384f7-20e6-4642-bef9-985b2cd6e5b4",
    name: "TREASURE HUNT",
    mode: "offline",
    min: 4,
    max: 5,
    coordinators: [
      { name: "", phone: "" },
      { name: "", phone: "" },
    ],
    rules: 1,
  },
  {
    eventId: "event_89b99c68-ecb5-4f95-970a-d5a344d4f7b2",
    name: "FACE PAINTING",
    mode: "offline",
    min: 1,
    max: 1,
    coordinators: [
      { name: "", phone: "" },
      { name: "", phone: "" },
    ],
    rules: 1,
  },
  {
    eventId: "event_7d07ade7-3c29-4173-a4d8-44c6c84fb1c3",
    name: "SLAM POETRY",
    mode: "offline",
    min: 1,
    max: 1,
    coordinators: [
      { name: "", phone: "" },
      { name: "", phone: "" },
    ],
    rules: 1,
  },
  {
    eventId: "event_58181ba4-ae01-4659-bf6f-67da951630f1",
    name: "PHOTOGRAPHY",
    mode: "offline",
    min: 1,
    max: 1,
    coordinators: [
      { name: "", phone: "" },
      { name: "", phone: "" },
    ],
    rules: 1,
  },
  {
    eventId: "event_4168b179-80a0-40aa-b639-2c0fa061618a",
    name: "FUTSAL",
    mode: "offline",
    min: 5,
    max: 8,
    coordinators: [
      { name: "", phone: "" },
      { name: "", phone: "" },
    ],
    rules: 1,
  },
  {
    eventId: "event_a5dc2d0f-67c1-4a9e-aeb1-3a2b0e39fe01",
    name: "COD MOBILE",
    mode: "online",
    min: 4,
    max: 4,
    coordinators: [
      { name: "", phone: "" },
      { name: "", phone: "" },
    ],
    rules: 1,
  },
  {
    eventId: "event_a794c619-fd76-48af-9b6d-fa0cfde88ad0",
    name: "FIFA",
    mode: "online",
    min: 1,
    max: 2,
    coordinators: [
      { name: "", phone: "" },
      { name: "", phone: "" },
    ],
    rules: 2,
  },
];

import sricharan from "./Assets/Images/team/sricharan.webp";
import george from "./Assets/Images/team/george.webp";
import sai from "./Assets/Images/team/sai.webp";
import drishti from "./Assets/Images/team/drishti.webp";
import gowtham from "./Assets/Images/team/gowtham.webp";
import sunil from "./Assets/Images/team/sunil.webp";
import sriram from "./Assets/Images/team/sriram.webp";
import brijesh from "./Assets/Images/team/brijesh.webp";
import aashiq from "./Assets/Images/team/aashiq.webp";
import ruby from "./Assets/Images/team/ruby.webp";
import dharun from "./Assets/Images/team/dharun.jpeg";
// import david from "./Assets/Images/team/david.webp";
import dinesh from "./Assets/Images/team/dinesh.webp";
import harish from "./Assets/Images/team/harish.webp";
import harshithan from "./Assets/Images/team/harshithan.webp";
import Karthik from "./Assets/Images/team/Karthik.webp";
import manoj from "./Assets/Images/team/manoj.webp";
import mruthula from "./Assets/Images/team/mruthula.webp";
import Mukesh from "./Assets/Images/team/Mukesh.webp";
import nagaraj from "./Assets/Images/team/nagaraj.webp";
import nausheen from "./Assets/Images/team/nausheen.webp";
import Rahul_s from "./Assets/Images/team/Rahul_s.webp";
import sreelakshmi from "./Assets/Images/team/sreelakshmi.webp";
import Venkatesh from "./Assets/Images/team/Vengatesh.webp";
import vineethram from "./Assets/Images/team/vineethram.webp";
import kavya from "./Assets/Images/team/kavya.webp";
import p from "./Assets/Images/team/p.webp";
// import kcg from "./Assets/Images/team/kcg.webp";
import anand from "./Assets/Images/team/anand.webp";
import annie from "./Assets/Images/team/annie.webp";
import easu from "./Assets/Images/team/easu.webp";
import elizabeth from "./Assets/Images/team/elizabeth.webp";
import enid from "./Assets/Images/team/enid.webp";

import dummy from "./Assets/Images/team/dummy.webp";

// Sponsorship and support
// Sreelakshmi
// Gowtham
// Brijesh
// Drishti
// Kavya
// Vineeth

// Media
// Sunil
// Sriram

// Tech

export const teams = {
  management: {
    name: "Chief Patrons",
    members: [
      {
        name: "Dr. Elizabeth Verghese",
        img: elizabeth,
        desc: "Founder Chairperson - Hindustan Group of Institutions",
      },
      {
        name: "Dr. Anand Jacob Verghese",
        img: anand,
        desc: "Chairman - Hindustan Group of Institutions",
      },
      {
        name: "Dr. Annie Jacob",
        img: annie,
        desc: "Director - KCG College Of Technology",
      },
      {
        name: "Mr. Enid Verghese Jacob",
        img: enid,
        desc: "Deputy Director - Hindustan Group of Institutions",
      },
    ],
  },
  pc: {
    name: "Patrons",
    members: [
      {
        name: "Dr. M Muthukannan",
        img: p,
        desc: "Principal - KCG College Of Technology",
      },
      {
        name: "Dr. D Easu",
        img: easu,
        desc: "Head/Student Affairs - KCG College Of Technology",
      },
    ],
  },
  core: {
    name: "Core Team",
    members: [
      {
        name: "George ",
        img: george,
        dept: depts.cs,
        insta: "https://instagram.com/george__britt?igshid=MzRlODBiNWFlZA==",
      },
      {
        name: "Sricharan",
        img: sricharan,
        dept: depts.ad,
        insta: "https://instagram.com/sricharan_phnx?igshid=MzRlODBiNWFlZA==",
      },
      {
        name: "Sai Aravind",
        img: sai,
        dept: depts.cs,
        insta: "https://instagram.com/ft_sai_arvind?igshid=MzRlODBiNWFlZA==",
      },
      {
        name: "Aashiq ",
        img: aashiq,
        dept: depts.ad,
        insta: "https://instagram.com/__a.a.s.h.i.q__?igshid=MzRlODBiNWFlZA==",
      },
      {
        name: "Rubasri",
        img: ruby,
        dept: depts.cs,
        insta: "https://instagram.com/rubysaravanan08?igshid=MzRlODBiNWFlZA==",
      },
    ],
  },
  tech: {
    name: "Tech",
    members: [{ name: "Dharun V S", img: dharun, dept: depts.ad }],
  },
  media: {
    name: "Media Team",
    members: [
      { name: "Sunil Kumar", img: sunil, dept: depts.ad },
      { name: "Sriram", img: sriram, dept: depts.it },
    ],
  },
  support: {
    name: "Support & Sponsorship",
    members: [
      { name: "Sreelakshmi", img: sreelakshmi, dept: depts.ad },
      { name: "Gowtham", img: gowtham, dept: depts.ad },
      { name: "Brijesh", img: brijesh, dept: depts.ao },
      { name: "Drishti", img: drishti, dept: depts.cs },
      { name: "Kavya", img: kavya, dept: depts.cs },
      { name: "Vineeth", img: vineethram, dept: depts.ae },
      { name: "Shaan", img: dummy, dept: depts.ft },
    ],
  },
  committee: {
    name: "Committee",
    members: [
      { name: "NAUSHEEN A L", img: nausheen, dept: depts.ft },
      { name: "MRUTHULA", img: mruthula, dept: depts.ce },
      { name: "HARISH ", img: harish, dept: depts.ad },
      { name: "RAHUL S", img: Rahul_s, dept: depts.mc },
      { name: "NAGARAJ S", img: nagaraj, dept: depts.ei },
      { name: "HARSHITHAN", img: harshithan, dept: depts.it },
      { name: "MUKESH  M", img: Mukesh, dept: depts.me },
      { name: "DINESH S", img: dinesh, dept: depts.ee },
      { name: "VENGATESH", img: Venkatesh, dept: depts.cs },
      { name: "KARTHIK K", img: Karthik, dept: depts.ec },
      { name: "MANOJ KUMAR", img: manoj, dept: depts.at },
      { name: "THANUSH J", img: dummy, dept: depts.ae },
    ],
  },
  contact: {
    name: "Media Team",
    members: [
      {
        name: "Sricharan",
        img: sricharan,
        dept: depts.ad,
        phone: "Ph. 63806 88350",
      },
      {
        name: "George Britt",
        img: george,
        dept: depts.cs,
        phone: "Ph. 95147 90999",
      },
    ],
  },
};

export const baseURL = "http://localhost:8000";
// export const baseURL = "https://laksh-358718.el.r.appspot.com";
